export enum ErrorCode {
  // Authentication errors
  LOGIN_FAILED = 'LOGIN_FAILED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_VERIFICATION_CODE = 'INVALID_VERIFICATION_CODE',
  CONFLICTING_VERIFICATION_CODE = 'CONFLICTING_VERIFICATION_CODE',
  EXPIRED_VERIFICATION_CODE = 'EXPIRED_VERIFICATION_CODE',

  // User errors
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',

  // Resource errors
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
  FORBIDDEN_ACTION = 'FORBIDDEN_ACTION',

  // Server errors
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR = 'DATABASE_ERROR',

  // Generic errors
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  OPERATION_FAILED = 'OPERATION_FAILED',

  // Input validation errors
  INVALID_INPUT = 'INVALID_INPUT',

  // Email
  INVALID_EMAIL = 'INVALID_EMAIL',
  REQUIRED_EMAIL = 'REQUIRED_EMAIL',
  EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND',

  // Password
  REQUIRED_PASSWORD = 'REQUIRED_PASSWORD',
  REQUIRED_CONFIRM_PASSWORD = 'REQUIRED_CONFIRM_PASSWORD',
  NEW_PASSWORD_MUST_BE_DIFFERENT = 'NEW_PASSWORD_MUST_BE_DIFFERENT',
  PASSWORDS_DONT_MATCH = 'PASSWORDS_DONT_MATCH',
  PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  PASSWORD_TOO_WEAK = 'PASSWORD_TOO_WEAK',

  // Verification code
  REQUIRED_VERIFICATION_CODE = 'REQUIRED_VERIFICATION_CODE',
  MIN_VERIFICATION_CODE_LENGTH = 'MIN_VERIFICATION_CODE_LENGTH',

  // Name
  REQUIRED_FIRST_NAME = 'REQUIRED_FIRST_NAME',
  REQUIRED_LAST_NAME = 'REQUIRED_LAST_NAME',
}
